apiVersion: v1
kind: Service
metadata:
  name: {{ include "helios.fullname" . }}
  labels:
    {{- include "helios.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "helios.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
    {{- end }}
    {{- if .Values.adminAPI.enabled }}
    - name: admin
      port: {{ .Values.adminAPI.port }}
      targetPort: {{ .Values.adminAPI.port }}
    {{- end }}
